function tests = test_fft_frequency_bins
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(repoRoot, 'src')));
testCase.TestData.repoRoot = repoRoot;
end

function testReturnsExactly512FrequencyBins(testCase)
fs = 44100;
t = (0:fs-1).' / fs;
x = sin(2 * pi * 1000 * t);

segment = struct( ...
    'id', 'fft_test', ...
    'audio_file', "", ...
    'label_file', "", ...
    'label_text', "", ...
    't_start_sec', 0, ...
    't_end_sec', 1, ...
    't_center_sec', 0.5, ...
    'pad_left_sec', 0, ...
    'pad_right_sec', 0, ...
    'segment_start_sec', 0, ...
    'segment_end_sec', 1, ...
    'sample_rate', fs, ...
    'num_samples', numel(x), ...
    'audio', x, ...
    'sample_start_idx', 1, ...
    'sample_end_idx', numel(x));

fftResult = fft_calc(segment);

verifyEqual(testCase, size(fftResult.spectrogram_db, 1), 512);
verifyEqual(testCase, numel(fftResult.freq_hz), 512);
verifyTrue(testCase, fftResult.freq_hz(end) < fs / 2);
end

function testBandSelectionAllowsFullNyquistRequest(testCase)
freqHz = linspace(0, 22006.93359375, 512).';

[selectedIdx, selectedFreqHz, freqBandHz, meta] = ...
    select_frequency_bins(freqHz, "band", 1000, [0 22050]);

verifyEqual(testCase, selectedIdx(:), (1:512).');
verifyEqual(testCase, selectedFreqHz(:), freqHz);
verifyEqual(testCase, freqBandHz, [0 22050], 'AbsTol', 1e-9);
verifyEqual(testCase, meta.mode, "band");
end
