function tests = test_build_run_metadata
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(repoRoot, 'src')));
testCase.TestData.repoRoot = repoRoot;
end

function testBuildsMetadataFromExplicitValues(testCase)
metadata = build_run_metadata( ...
    "C:\audio.wav", ...
    "", ...
    "C:\out", ...
    2.0, ...
    3.0, ...
    30.0, ...
    0.0, ...
    "single", ...
    900, ...
    [800 1200], ...
    "quantile", ...
    5, ...
    0.5, ...
    1.0, ...
    10, ...
    true, ...
    0.95);

verifyEqual(testCase, metadata.audio_path, "C:\audio.wav");
verifyEqual(testCase, metadata.frequency_mode, "single");
verifyEqual(testCase, metadata.binning_type, "quantile");
verifyEqual(testCase, metadata.n_perms, 10);
verifyEqual(testCase, metadata.ci_level, 0.95);
end
