function summary = run_mi_pipeline_core( ...
    audio_path, label_path, output_dir, ...
    pad_left_sec, pad_right_sec, ...
    segment_duration_sec, segment_overlap_sec, ...
    frequency_mode, target_hz, range_hz, ...
    binning_type, n_bins, ...
    max_delay_sec, window_duration_sec, n_perms, ...
    save_segment_preview, ci_level)
%RUN_MI_PIPELINE_CORE Внутренняя функция запуска пайплайна.

repo_root = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(repo_root, 'src')));

if ~isfolder(output_dir)
    mkdir(output_dir);
end

dataset = prepare_data( ...
    audio_path, label_path, ...
    pad_left_sec, pad_right_sec, ...
    segment_duration_sec, segment_overlap_sec);
segment_count = numel(dataset.segments);
run_metadata = build_run_metadata( ...
    audio_path, label_path, output_dir, ...
    pad_left_sec, pad_right_sec, ...
    segment_duration_sec, segment_overlap_sec, ...
    frequency_mode, target_hz, range_hz, ...
    binning_type, n_bins, ...
    max_delay_sec, window_duration_sec, n_perms, ...
    save_segment_preview, ci_level);

summary = struct();
summary.repo_root = repo_root;
summary.output_dir = string(output_dir);
summary.mode = dataset.mode;
summary.segment_count = segment_count;
summary.results = repmat(struct( ...
    'segment_id', "", ...
    'mat_path', "", ...
    'plot_path', "", ...
    'preview_path', "", ...
    'selected_freq_hz', [], ...
    'freq_band_hz', []), segment_count, 1);

for si = 1:segment_count
    segment = dataset.segments(si);
    fprintf('[%d/%d] Сегмент %s\n', si, segment_count, segment.id);

    fft_result = fft_calc(segment);
    [selected_idx, selected_freq_hz, freq_band_hz, selection_meta] = ...
        select_frequency_bins(fft_result.freq_hz, frequency_mode, target_hz, range_hz);

    selected_db = fft_result.spectrogram_db(selected_idx, :);

    switch lower(string(binning_type))
        case "quantile"
            [bin_matrix, bin_edges, binning_meta] = ...
                binning_quantile(selected_db, n_bins);
        case "uniform"
            [bin_matrix, bin_edges, binning_meta] = ...
                binning_uniform(selected_db, n_bins);
        otherwise
            error('Неподдерживаемый тип бининга: %s', string(binning_type));
    end

    binning_meta.selected_frequency_indices = selected_idx;
    binning_meta.selected_frequency_hz = selected_freq_hz;
    binning_meta.selection_meta = selection_meta;
    binning_meta.bin_edges = bin_edges;

    mi_result = calc_mi_profile( ...
        bin_matrix, ...
        fft_result, ...
        selected_idx, ...
        selected_freq_hz, ...
        freq_band_hz, ...
        max_delay_sec, ...
        window_duration_sec, ...
        n_perms, ...
        binning_meta, ...
        segment);

    [mat_path, saved_payload] = save_mi_result( ...
        segment, fft_result, binning_meta, mi_result, output_dir, run_metadata);

    plot_path = fullfile(output_dir, sprintf('%s_mi_profile.png', segment.id));
    plot_mi_standard(segment, fft_result, saved_payload.mi_result, plot_path, ci_level);

    preview_path = "";
    if save_segment_preview
        preview_path = fullfile(output_dir, sprintf('%s_segment_preview.png', segment.id));
        plot_segment_preview(segment, fft_result, preview_path);
    end

    summary.results(si).segment_id = segment.id;
    summary.results(si).mat_path = string(mat_path);
    summary.results(si).plot_path = string(plot_path);
    summary.results(si).preview_path = string(preview_path);
    summary.results(si).selected_freq_hz = selected_freq_hz;
    summary.results(si).freq_band_hz = freq_band_hz;
end

save(fullfile(output_dir, 'run_summary.mat'), 'summary', 'run_metadata', 'dataset');
fprintf('Готово. Результаты сохранены в: %s\n', output_dir);
end
