function summary = run_mi_pipeline_core( ...
    audio_path, label_path, output_dir, ...
    pad_left_sec, pad_right_sec, ...
    segment_duration_sec, segment_overlap_sec, ...
    frequency_mode, target_hz, range_hz, ...
    binning_type, n_bins, ...
    max_delay_sec, window_duration_sec, n_perms, ...
    save_segment_preview, ci_level, ...
    write_tensor_shards, max_tensor_shard_size_mb, tensor_shard_mat_format, ...
    plain_processing_mode, save_window_matrices, save_file_level_tensor, window_matrix_mat_format, ...
    use_mex_backend)
%RUN_MI_PIPELINE_CORE Внутренняя функция запуска пайплайна.

repo_root = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(repo_root, 'src')));

if ~isfolder(output_dir)
    mkdir(output_dir);
end

run_metadata = build_run_metadata( ...
    audio_path, label_path, output_dir, ...
    pad_left_sec, pad_right_sec, ...
    segment_duration_sec, segment_overlap_sec, ...
    frequency_mode, target_hz, range_hz, ...
    binning_type, n_bins, ...
    max_delay_sec, window_duration_sec, n_perms, ...
    save_segment_preview, ci_level, ...
    write_tensor_shards, max_tensor_shard_size_mb, tensor_shard_mat_format, ...
    plain_processing_mode, save_window_matrices, save_file_level_tensor, window_matrix_mat_format, ...
    use_mex_backend);

if strlength(string(label_path)) == 0
    [summary, dataset] = run_plain_mode( ...
        audio_path, output_dir, ...
        frequency_mode, target_hz, range_hz, ...
        binning_type, n_bins, ...
        max_delay_sec, window_duration_sec, n_perms, ...
        save_segment_preview, ci_level, ...
        write_tensor_shards, max_tensor_shard_size_mb, tensor_shard_mat_format, ...
        plain_processing_mode, save_window_matrices, save_file_level_tensor, window_matrix_mat_format, ...
        use_mex_backend, ...
        run_metadata, repo_root);
else
    [summary, dataset] = run_annotated_mode( ...
        audio_path, label_path, output_dir, ...
        pad_left_sec, pad_right_sec, ...
        segment_duration_sec, segment_overlap_sec, ...
        frequency_mode, target_hz, range_hz, ...
        binning_type, n_bins, ...
        max_delay_sec, window_duration_sec, n_perms, ...
        save_segment_preview, ci_level, ...
        write_tensor_shards, max_tensor_shard_size_mb, tensor_shard_mat_format, ...
        run_metadata, repo_root);
end

save(fullfile(output_dir, 'run_summary.mat'), '-v7.3', 'summary', 'run_metadata', 'dataset');
fprintf('Готово. Результаты сохранены в: %s\n', output_dir);
end

function [summary, dataset] = run_plain_mode( ...
    audio_path, output_dir, ...
    frequency_mode, target_hz, range_hz, ...
    binning_type, n_bins, ...
    max_delay_sec, window_duration_sec, n_perms, ...
    save_segment_preview, ci_level, ...
    write_tensor_shards, max_tensor_shard_size_mb, tensor_shard_mat_format, ...
    plain_processing_mode, save_window_matrices, save_file_level_tensor, window_matrix_mat_format, ...
    use_mex_backend, run_metadata, repo_root)

if lower(string(plain_processing_mode)) ~= "file_global_binning"
    error('Для plain-режима поддерживается только plain_processing_mode = "file_global_binning"');
end

audio_files = find_audio_files(audio_path);
dataset = struct();
dataset.mode = "plain";
dataset.processing_mode = string(plain_processing_mode);
dataset.source_audio = audio_files;
dataset.source_labels = "";
dataset.created_at = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

item_count = numel(audio_files);
summary = init_summary(repo_root, output_dir, "plain", item_count);
summary.plain_processing_mode = string(plain_processing_mode);

for ai = 1:item_count
    audio_file = audio_files(ai);
    [~, base_name, ~] = fileparts(audio_file);
    item_id = string(base_name);
    fprintf('[%d/%d] Файл %s\n', ai, item_count, item_id);
    summary.results(ai).item_id = item_id;

    try
        file_summary = process_plain_file_global_binning( ...
            audio_file, output_dir, ...
            frequency_mode, target_hz, range_hz, ...
            binning_type, n_bins, ...
            max_delay_sec, window_duration_sec, n_perms, ...
            save_window_matrices, window_matrix_mat_format, ...
            save_file_level_tensor, write_tensor_shards, max_tensor_shard_size_mb, tensor_shard_mat_format, ...
            save_segment_preview, ci_level, run_metadata, use_mex_backend);

        summary.results(ai).status = "ok";
        summary.results(ai).error_message = "";
        summary.results(ai).file_result_path = string(file_summary.file_result_path);
        summary.results(ai).mat_path = "";
        summary.results(ai).plot_path = "";
        summary.results(ai).preview_path = string(file_summary.preview_path);
        summary.results(ai).window_count = file_summary.window_count;
        summary.results(ai).selected_freq_hz = file_summary.selected_freq_hz;
        summary.results(ai).freq_band_hz = file_summary.freq_band_hz;
        summary.results(ai).timing = file_summary.timing;
    catch ME
        warning('Файл %s пропущен: %s', item_id, ME.message);
        summary.results(ai).status = "failed";
        summary.results(ai).error_message = string(ME.message);
        summary.results(ai).file_result_path = "";
        summary.results(ai).mat_path = "";
        summary.results(ai).plot_path = "";
        summary.results(ai).preview_path = "";
        summary.results(ai).window_count = 0;
        summary.results(ai).selected_freq_hz = [];
        summary.results(ai).freq_band_hz = [];
        summary.results(ai).timing = struct();
    end
end
end

function [summary, dataset] = run_annotated_mode( ...
    audio_path, label_path, output_dir, ...
    pad_left_sec, pad_right_sec, ...
    segment_duration_sec, segment_overlap_sec, ...
    frequency_mode, target_hz, range_hz, ...
    binning_type, n_bins, ...
    max_delay_sec, window_duration_sec, n_perms, ...
    save_segment_preview, ci_level, ...
    write_tensor_shards, max_tensor_shard_size_mb, tensor_shard_mat_format, ...
    run_metadata, repo_root)

dataset = prepare_data( ...
    audio_path, label_path, ...
    pad_left_sec, pad_right_sec, ...
    segment_duration_sec, segment_overlap_sec);
segment_count = numel(dataset.segments);

summary = init_summary(repo_root, output_dir, dataset.mode, segment_count);

for si = 1:segment_count
    segment = dataset.segments(si);
    fprintf('[%d/%d] Сегмент %s\n', si, segment_count, segment.id);
    summary.results(si).item_id = segment.id;

    try
        fft_result = fft_calc(segment);
        [selected_idx, selected_freq_hz, freq_band_hz, selection_meta] = ...
            select_frequency_bins(fft_result.freq_hz, frequency_mode, target_hz, range_hz);

        selected_db = fft_result.spectrogram_db(selected_idx, :);

        switch lower(string(binning_type))
            case "quantile"
                [bin_matrix, bin_edges, binning_meta] = ...
                    binning_quantile(selected_db, n_bins);
            case "uniform"
                [bin_matrix, bin_edges, binning_meta] = ...
                    binning_uniform(selected_db, n_bins);
            otherwise
                error('Неподдерживаемый тип бининга: %s', string(binning_type));
        end

        binning_meta.selected_frequency_indices = selected_idx;
        binning_meta.selected_frequency_hz = selected_freq_hz;
        binning_meta.selection_meta = selection_meta;
        binning_meta.bin_edges = bin_edges;

        mi_result = calc_mi_profile( ...
            bin_matrix, ...
            fft_result, ...
            selected_idx, ...
            selected_freq_hz, ...
            freq_band_hz, ...
            max_delay_sec, ...
            window_duration_sec, ...
            n_perms, ...
            binning_meta, ...
            segment);

        [mat_path, ~] = save_mi_result( ...
            segment, fft_result, binning_meta, mi_result, output_dir, run_metadata, ...
            write_tensor_shards, max_tensor_shard_size_mb, tensor_shard_mat_format);

        plot_path = fullfile(output_dir, sprintf('%s_mi_profile.png', segment.id));
        plot_mi_standard(segment, fft_result, mi_result, plot_path, ci_level);

        preview_path = "";
        if save_segment_preview
            preview_path = fullfile(output_dir, sprintf('%s_segment_preview.png', segment.id));
            plot_segment_preview(segment, fft_result, preview_path);
        end

        summary.results(si).status = "ok";
        summary.results(si).error_message = "";
        summary.results(si).file_result_path = "";
        summary.results(si).mat_path = string(mat_path);
        summary.results(si).plot_path = string(plot_path);
        summary.results(si).preview_path = string(preview_path);
        summary.results(si).window_count = size(mi_result.mi_values, 3);
        summary.results(si).selected_freq_hz = selected_freq_hz;
        summary.results(si).freq_band_hz = freq_band_hz;
        summary.results(si).timing = struct();
    catch ME
        warning('Сегмент %s пропущен: %s', segment.id, ME.message);
        summary.results(si).status = "failed";
        summary.results(si).error_message = string(ME.message);
        summary.results(si).file_result_path = "";
        summary.results(si).mat_path = "";
        summary.results(si).plot_path = "";
        summary.results(si).preview_path = "";
        summary.results(si).window_count = 0;
        summary.results(si).selected_freq_hz = [];
        summary.results(si).freq_band_hz = [];
        summary.results(si).timing = struct();
    end
end
end

function summary = init_summary(repo_root, output_dir, mode, item_count)
summary = struct();
summary.repo_root = repo_root;
summary.output_dir = string(output_dir);
summary.mode = string(mode);
summary.item_count = item_count;
summary.results = repmat(struct( ...
    'item_id', "", ...
    'status', "", ...
    'error_message', "", ...
    'file_result_path', "", ...
    'mat_path', "", ...
    'plot_path', "", ...
    'preview_path', "", ...
    'window_count', 0, ...
    'selected_freq_hz', [], ...
    'freq_band_hz', [], ...
    'timing', struct()), item_count, 1);
end
